package com.rmehub.chat.constant;

public enum ResponseCode {

    API_SUCCESS,
    API_ERROR,
    REQUEST_SENT, CHAT_REQUEST_SENT, NEW_CHAT_REQUEST, NOT_FOUND, FATAL_EXCEPTION, DUPLICATE_REQUEST, CR_FOUND, CHAT_REQUEST_MISMATCH, CHAT_REQUEST_REJECTED, CHAT_REQUEST_REJECT_SUCCESS, CHANNEL_FOUND, CR_ACCEPT_SUCCESS;

}
